//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Suburb { get; set; }
        public int Rooms { get; set; }
        public decimal Bathrooms { get; set; }
        public int Carports { get; set; }
    }
}
